# Generated by Django 2.1 on 2019-03-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='Uploaded_at',
            new_name='uploaded_at',
        ),
    ]
